export const USER_ERROR = 'USER_ERROR';
export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';
export const SIGNUP = 'SIGNUP';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const CREATE_POST = 'CREATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const POST_ERROR = 'POST_ERROR';
export const FETCH_POSTS = 'FETCH_POSTS';
export const POST_LOADING = 'POST_LOADING';

export const LIKE_POST = 'LIKE_POST';

export const RETWEET_POST = 'RETWEET_POST';
export const UNRETWEET_POST = 'UNRETWEET_POST';
export const RETWEET_LOADING = 'RETWEET_LOADING';

export const REPLY_TO_POST = 'REPLY_TO_POST';

export const VIEW_SINGLE_POST = 'VIEW_SINGLE_POST';

export const FOLLOW_USER = 'FOLLOW_USER';

export const CHANGE_PROFILE_PIC = 'CHANGE_PROFILE_PIC';
export const CHANGE_COVER_PHOTO = 'CHANGE_COVER_PHOTO';

export const PIN_POST = 'PIN_POST';


export const FETCH_USERS = 'FETCH_USERS';
export const USERS_LOADING = 'USERS_LOADING';
export const CLEAR_USER_SEARCH = 'CLEAR_USER_SEARCH';


export const CREATE_CHAT = 'CREATE_CHAT';
export const CHAT_LOADING = 'CHAT_LOADING';
export const FETCH_CHAT_MESSAGES = 'FETCH_CHAT_MESSAGES';
export const CHAT_MESSAGES_ERROR = 'CHAT_MESSAGES_ERROR';
export const CHANGE_CHAT_NAME = 'CHANGE_CHAT_NAME';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
export const UPDATE_LATEST_MESSAGE = 'UPDATE_LATEST_MESSAGE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';


export const NOTIFICATIONS_LOADING = 'NOTIFICATIONS_LOADING';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const MARK_READ = 'MARK_READ';